
spring:
  application:
    name: demo-dubbo-user
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    web-application-type: none
dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
    protocol: tri
  protocol:
    name: tri
    port: 50051
    id: tri
  provider:
    filter: saTokenFilter
  registry:
    address: nacos://localhost:8848?username=nacos&password=nacos
    register-mode: instance
    protocol: nacos
  config-center:
    address: nacos://localhost:8848?username=nacos&password=nacos
  metadata-report:
    address: nacos://localhost:8848?username=nacos&password=nacos
    username: nacos
    password: nacos
  metrics:
    enable-metadata: false


